# Generated by Django 5.1.8 on 2026-09-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_footersettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='facebook_fans',
            field=models.CharField(blank=True, default='19,243 Fans', help_text='Facebook fan count display text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='twitter_followers',
            field=models.CharField(blank=True, default='2,076 Followers', help_text='Twitter/X follower count display text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='youtube_subscribers',
            field=models.CharField(blank=True, default='15,200 Followers', help_text='YouTube subscriber count display text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel link', null=True),
        ),
    ]
