# Generated by Django 5.2.6 on 2026-08-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_add', '0002_alter_advertisement_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_code',
            field=models.TextField(),
        ),
    ]
