# Generated by Django 5.2.6 on 2026-04-29 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0007_alter_blogpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Toggle ON to show this post in the homepage carousel/hero section', verbose_name='Featured (Homepage Hero)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('edited', 'Edited - Pending Approval'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='HomepageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('carousel', 'Hero Carousel (Top Featured)'), ('blog_grid', 'Blog Grid Section'), ('latest_news', 'Latest News Section'), ('cat_section_1', 'Category Section 1'), ('cat_section_2', 'Category Section 2'), ('cat_section_3', 'Category Section 3'), ('most_viewed', 'Most Viewed Section')], max_length=50, unique=True)),
                ('title', models.CharField(blank=True, help_text='Override section heading (optional)', max_length=200)),
                ('post_count', models.PositiveIntegerField(default=6, help_text='How many posts to show')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on homepage')),
                ('category', models.ForeignKey(blank=True, help_text='Filter posts by this category (leave blank = all categories)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_post.category')),
            ],
            options={
                'verbose_name': 'Homepage Section Config',
                'verbose_name_plural': 'Homepage Section Configs',
                'ordering': ['order'],
            },
        ),
    ]
