# Generated by Django 5.2.6 on 2026-08-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0008_blogpost_is_featured_alter_blogpost_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compnay_logo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
