# Generated by Django 5.2.6 on 2026-08-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0009_compnay_logo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='font_awesome_icon',
            field=models.CharField(blank=True, default='layers', help_text='e.g: layers, tag, heart', max_length=500, null=True, verbose_name='Lucide icon name'),
        ),
    ]
