# Generated by Django 5.2.6 on 2026-08-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0010_alter_category_font_awesome_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='font_awesome_icon',
            field=models.CharField(blank=True, default='layers', max_length=500, null=True, verbose_name='Lucide icon name'),
        ),
    ]
