# Generated by Django 5.2.6 on 2026-08-18 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0011_subcategory_font_awesome_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='ai_model',
            field=models.CharField(blank=True, help_text='AI model identifier used for generation', max_length=100, null=True, verbose_name='AI Model'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='automation_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when article was generated by automation', null=True, verbose_name='Automation Created At'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='automation_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique pipeline execution identifier', max_length=255, null=True, verbose_name='Automation ID'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='factual_accuracy_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Factual Accuracy Score (0-100)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='generated_by_ai',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether content was generated by AI', verbose_name='Generated by AI'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_processing_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('downloaded', 'Downloaded'), ('processed', 'Processed'), ('failed', 'Failed'), ('placeholder', 'Placeholder Used')], db_index=True, default='not_started', max_length=20, verbose_name='Image Processing Status'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='language_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Language Score (0-100)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='original_content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='MD5 hash of original source content', max_length=64, null=True, verbose_name='Original Content Hash'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='original_title',
            field=models.TextField(blank=True, help_text='Original title from source', null=True, verbose_name='Original Title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='quality_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Quality Score (0-100)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='review_decision',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='not_reviewed', max_length=20, verbose_name='Review Decision'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='review_notes',
            field=models.TextField(blank=True, default='', help_text='Internal reviewer findings or notes', verbose_name='Review Notes'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reviewer_model',
            field=models.CharField(blank=True, help_text='AI model identifier used for automated review', max_length=100, null=True, verbose_name='Reviewer Model'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SEO Score (0-100)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='source_author',
            field=models.CharField(blank=True, help_text='Original author or reporter name', max_length=255, null=True, verbose_name='Source Author'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='source_image_url',
            field=models.URLField(blank=True, help_text='Original source image URL', max_length=500, null=True, verbose_name='Source Image URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='source_name',
            field=models.CharField(blank=True, help_text='Original publisher or website name', max_length=255, null=True, verbose_name='Source Name'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='source_published_at',
            field=models.DateTimeField(blank=True, help_text='Original publication timestamp', null=True, verbose_name='Source Published At'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='source_url',
            field=models.URLField(blank=True, db_index=True, help_text='Original article URL', max_length=500, null=True, verbose_name='Source URL'),
        ),
    ]
