# Generated by Django 5.2.6 on 2026-08-19 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0012_blogpost_ai_model_blogpost_automation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationPublishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('event_type', models.CharField(choices=[('request_received', 'Request Received'), ('idempotent_replay', 'Idempotent Replay'), ('published', 'Published'), ('rejected', 'Rejected'), ('conflict', 'Conflict'), ('throttled', 'Throttled'), ('disabled', 'Disabled'), ('processing_failed', 'Processing Failed')], max_length=50)),
                ('result_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('http_status', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('image_status', models.CharField(blank=True, max_length=100, null=True)),
                ('review_decision', models.CharField(blank=True, max_length=50, null=True)),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('factual_accuracy_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seo_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_logs', to='blog_post.blogpost')),
            ],
            options={
                'verbose_name': 'Automation Publish Log',
                'verbose_name_plural': 'Automation Publish Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='blog_post_a_event_t_a1726e_idx')],
            },
        ),
    ]
