# Generated by Django 5.1.8 on 2026-09-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0016_companyclient_companyclientfocus_companylocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Business Email'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Business Phone'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='trade_license',
            field=models.FileField(blank=True, null=True, upload_to='trade_licenses/', verbose_name='Trade License / Registration Document'),
        ),
    ]
