# Generated by Django 5.1.8 on 2026-09-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0017_blogpost_company_email_blogpost_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
