# Generated by Django 5.1.8 on 2026-09-02 09:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0018_blogpost_is_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='company_employees_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Employees Count (e.g., 50-249)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='company_founded_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Founded Year'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='company_hourly_rate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hourly Rate (e.g., $25 - $49 / hr)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='company_min_project_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Min. Project Size (e.g., $10,000+)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='company_website',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Website URL'),
        ),
        migrations.CreateModel(
            name='CompanyIndustryFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_industry_focuses', to='blog_post.blogpost')),
            ],
            options={
                'ordering': ['-percentage'],
            },
        ),
    ]
