# Generated by Django 5.1.8 on 2026-09-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0019_blogpost_company_employees_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_company_category',
            field=models.BooleanField(default=False, verbose_name='Is Industry / Company Category'),
        ),
    ]
