# Generated by Django 5.2.6 on 2026-07-27 13:58

from django.db import migrations


def create_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Editor')
    Group.objects.get_or_create(name='Moderator')
    Group.objects.get_or_create(name='Admin')

def delete_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Editor', 'Moderator', 'Admin']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_groups, delete_default_groups),
    ]
