# Generated by Django 5.2.6 on 2026-07-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20260727_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotFoundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('referer', models.CharField(blank=True, max_length=1024, null=True)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
