# Generated by Django 5.2.6 on 2026-07-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0008_blogpost_is_featured_alter_blogpost_status_and_more'),
        ('dashboard', '0003_notfoundlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPostStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='blog_post.blogpost')),
            ],
            options={
                'unique_together': {('post', 'date')},
            },
        ),
    ]
