# Generated by Django 5.2.6 on 2026-08-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancesettings',
            name='custom_message',
            field=models.TextField(blank=True, help_text='Optional message to display on the maintenance screen.', null=True, verbose_name='Custom Message'),
        ),
    ]
