# Generated by Django 5.1.8 on 2026-09-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_add_gtm_meta_pixel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Website এর Favicon আপলোড করুন (Standard size: 32x32 or 16x16)', null=True, upload_to='site/favicon/'),
        ),
    ]
