# Generated by Django 5.1.8 on 2026-09-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Navbar-এ দেখানোর জন্য Website Logo আপলোড করুন (recommended: PNG with transparent background, height ~60px)', null=True, upload_to='site/logo/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Dark background-এ দেখানোর জন্য Logo (Optional)', null=True, upload_to='site/logo/'),
        ),
    ]
